[theme]
# The theme that your custom theme inherits from.
base = "light"
# Primary accent color.
primaryColor = "#ad1d25"
# Background color of the app.
backgroundColor = "#FFFFFF"
# Color used for almost all text.
textColor = "#1e4785"
# Color used for all links.
# This defaults to the resolved value of `blueTextColor`.
linkColor = "#1e4785"
# Whether or not links should be displayed with an underline.
linkUnderline = true
# The font family for all text, except code blocks.
font = "sans-serif"
